### ISSUE TITLE
Bug: https://maps.elastic.co/ gives blank page

### ISSUE THREAD

**Issue by hoebelix** [elastic/ems-landing-page#593]
Hi,

currently https://maps.elastic.co/ gives a blank page. It seems that the assets can't be loaded.

**Comment by jsanz** [comment]
Hi @hoebelix thanks for reporting. This may be a CDN issue. Try to do a hard refresh on your browser or load from a private window. It is working on my end (but I had to do that hard refresh I mentioned).

![Peek 2023-05-11 15-25](https://github.com/elastic/ems-landing-page/assets/188264/613d5755-81a9-436c-b62b-2ec422cd0550)


Mind also that you have also the same website versioned and available at

https://maps.elastic.co/v8.7/ 

I'm going to keep this open and try to confirm with other colleagues this is our CDN acting up.

**Comment by hoebelix** [comment]
Hi @jsanz,

thank you for your help. The second link https://maps.elastic.co/v8.7/ is working without problems. The URL  https://maps.elastic.co/  still gives a blank page. I tried this with different browsers, also with a private window. 

Attached is a screenshot of the networking panel in Firefox.


![Bildschirmfoto 2023-05-11 um 15 32 49](https://github.com/elastic/ems-landing-page/assets/26346227/10846f96-0dbb-44a9-9091-ed22f2f630f9)

**Comment by jsanz** [comment]
A colleague (from Canada, I'm based in Spain) confirmed it is working from him so it is definitely a CDN problem. Not sure if you should be able to get a fresh copy of the new `index.html` file by adding a random parameter, something like:

https://maps.elastic.co/?cache=invalidate

Anyways, I'll contact our infra team to get assistance to force the invalidation of that asset since the rest should have different names but unfortunately we cannot change the main entry point.

**Comment by hoebelix** [comment]
The random parameter thing didn't work. But I am happy now, because I can use https://maps.elastic.co/v8.7/ 
Time will solve the CDN problem :-)

Thanks again!
